spring:
  datasource:
    url: jdbc:mysql://localhost:3307/testdb
    username: test_user
    password: test_password
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true