version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: week2
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
      MYSQL_DATABASE: fcfs
      MYSQL_USER: user
      MYSQL_PASSWORD: qwer1234
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
